project:
  type: website

website:
  title: "Data Project Presentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Plot2.qmd
        text: Performance Analysis 
      - about.qmd
      - href: sources.qmd
        text: Sources
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



